package chai.ui;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/** Represents one message and its speaker in Chai's conversation view. */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;

    @FXML
    private Label avatar;

    /** Loads the reusable dialog layout and fills it with one message. */
    private DialogBox(String text, String avatarText, String styleClass) {
        FXMLLoader fxmlLoader = new FXMLLoader(DialogBox.class.getResource("/view/DialogBox.fxml"));
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);

        try {
            fxmlLoader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load the dialog box layout", e);
        }

        dialog.setText(text);
        avatar.setText(avatarText);
        getStyleClass().add(styleClass);
    }

    /**
     * Creates a right-aligned dialog for a user command.
     *
     * @param text Command entered by the user.
     * @return User dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, "YOU", "user-dialog");
    }

    /**
     * Creates a left-aligned dialog for a Chai response.
     *
     * @param text Response generated by Chai.
     * @return Chai dialog box.
     */
    public static DialogBox getChaiDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "C", "chai-dialog");
        dialogBox.flip();
        return dialogBox;
    }

    /** Places Chai's avatar before its response to distinguish the speakers. */
    private void flip() {
        getChildren().setAll(avatar, dialog);
        setAlignment(Pos.TOP_LEFT);
    }
}
